package store

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// helperScriptsDir holds the three fixed, type-specific helper scripts
// (dbBackupScript/logGenScript/logReconcileScript below) -- deployed once,
// idempotently, the same regenerate-then-fixed-install pattern as
// everything else in this feature set, rather than shipped via Debian
// packaging. Each per-task systemd unit's ExecStart calls the relevant
// fixed script with that task's own arguments (backup dir/retention,
// service name/day offset) -- the script content itself never varies
// per-task, only the arguments do, so one shared script per type is
// exactly right rather than templating a new script per task.
const helperScriptsDir = "/usr/lib/rivolution/scheduled-tasks"

const dbBackupScript = `#!/bin/sh
# Generated by rivapi's Scheduled Tasks page -- do not hand-edit, it will
# be overwritten the next time any db_backup task is created or deployed.
set -e
BACKUP_DIR="$1"
RETENTION="$2"

HOST=$(awk -F= '/^\[mySQL\]/{f=1;next}/^\[/{f=0}f&&$1=="Hostname"{print $2}' /etc/rd.conf)
DBUSER=$(awk -F= '/^\[mySQL\]/{f=1;next}/^\[/{f=0}f&&$1=="Loginname"{print $2}' /etc/rd.conf)
PASS=$(awk -F= '/^\[mySQL\]/{f=1;next}/^\[/{f=0}f&&$1=="Password"{print $2}' /etc/rd.conf)
DB=$(awk -F= '/^\[mySQL\]/{f=1;next}/^\[/{f=0}f&&$1=="Database"{print $2}' /etc/rd.conf)

mkdir -p "$BACKUP_DIR"
STAMP=$(date +%Y_%m_%d)
mysqldump -h "$HOST" -u "$DBUSER" -p"$PASS" "$DB" | gzip > "$BACKUP_DIR/${DB}_${STAMP}.sql.gz"

# Keep only the most recent $RETENTION backups.
COUNT=$(find "$BACKUP_DIR" -name "${DB}_*.sql.gz" | wc -l)
if [ "$COUNT" -gt "$RETENTION" ]; then
    find "$BACKUP_DIR" -name "${DB}_*.sql.gz" | sort | head -n "$((COUNT - RETENTION))" | xargs -r rm --
fi
`

const logGenScript = `#!/bin/sh
# Generated by rivapi's Scheduled Tasks page -- do not hand-edit.
set -e
DAYS_OFFSET="$1"
SERVICE="$2"
/usr/bin/rdlogmanager -P -d "$DAYS_OFFSET" -t -s "$SERVICE"
`

const logReconcileScript = `#!/bin/sh
# Generated by rivapi's Scheduled Tasks page -- do not hand-edit.
set -e
SERVICE="$1"
/usr/bin/rdlogmanager -r Reconcile -s "$SERVICE"
`

func helperScriptPath(t TaskType) string {
	switch t {
	case TaskDBBackup:
		return helperScriptsDir + "/db-backup.sh"
	case TaskLogGen:
		return helperScriptsDir + "/log-gen.sh"
	case TaskLogReconcile:
		return helperScriptsDir + "/log-reconcile.sh"
	default:
		return ""
	}
}

func helperScriptContent(t TaskType) string {
	switch t {
	case TaskDBBackup:
		return dbBackupScript
	case TaskLogGen:
		return logGenScript
	case TaskLogReconcile:
		return logReconcileScript
	default:
		return ""
	}
}

// ensureHelperScript deploys the fixed helper script for t if it isn't
// already present with the current content -- idempotent, called before
// every deploy so an upgraded rivapi binary's updated script content
// always reaches the box the next time any task of that type is touched.
func ensureHelperScript(t TaskType) error {
	path := helperScriptPath(t)
	if path == "" {
		return nil // TaskCustom has no fixed helper script
	}
	content := helperScriptContent(t)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		return nil
	}
	if err := sudoRun("mkdir", "-p", helperScriptsDir); err != nil {
		return err
	}
	staged, err := writeStaged("helper-"+string(t)+".sh", content)
	if err != nil {
		return err
	}
	if err := sudoRun("install", "-m", "755", staged, path); err != nil {
		return err
	}
	return nil
}

// execStartFor returns the ExecStart= command line for t, given its own
// configured arguments. CustomCommand is operator-authored, run via
// /bin/sh -c: the operator is the trusted admin of their own box entering
// their own command to run periodically, the same trust boundary crontab
// itself already grants them today -- see BACKLOG.md's tracked gap this
// page replaces.
func execStartFor(t ScheduledTask) (string, error) {
	switch t.Type {
	case TaskDBBackup:
		if t.BackupDir == "" || t.RetentionDays <= 0 {
			return "", fmt.Errorf("db_backup task needs a backup directory and a positive retention count")
		}
		return fmt.Sprintf("%s %s %d", helperScriptPath(TaskDBBackup), t.BackupDir, t.RetentionDays), nil
	case TaskLogGen:
		if t.ServiceName == "" {
			return "", fmt.Errorf("log_gen task needs a Rivendell service name")
		}
		return fmt.Sprintf("%s %d %s", helperScriptPath(TaskLogGen), t.DaysOffset, t.ServiceName), nil
	case TaskLogReconcile:
		if t.ServiceName == "" {
			return "", fmt.Errorf("log_reconcile task needs a Rivendell service name")
		}
		return fmt.Sprintf("%s %s", helperScriptPath(TaskLogReconcile), t.ServiceName), nil
	case TaskCustom:
		if strings.TrimSpace(t.CustomCommand) == "" {
			return "", fmt.Errorf("custom task needs a command")
		}
		return "/bin/sh -c " + shellQuote(t.CustomCommand), nil
	default:
		return "", fmt.Errorf("unknown task type %q", t.Type)
	}
}

// shellQuote wraps s in single quotes for safe use as one systemd
// ExecStart= argument, escaping any single quote s itself contains.
// Standard POSIX-shell single-quote escaping: close the quote, emit an
// escaped literal quote, reopen the quote.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// DeployTask (re)generates and installs t's service+timer unit pair, then
// enables the timer. Safe to call again for an existing task (e.g. after
// editing its schedule) -- systemd overwrites/reloads cleanly either way.
func DeployTask(t ScheduledTask) error {
	if !validTaskID(t.ID) {
		return fmt.Errorf("internal error: invalid task ID %q", t.ID)
	}
	if strings.TrimSpace(t.Schedule) == "" {
		return fmt.Errorf("task needs a schedule (systemd OnCalendar= expression)")
	}

	if err := ensureHelperScript(t.Type); err != nil {
		return fmt.Errorf("deploying helper script: %w", err)
	}

	execStart, err := execStartFor(t)
	if err != nil {
		return err
	}

	unit := TaskUnitName(t.ID)

	serviceContent := fmt.Sprintf(`# Generated by rivapi's Scheduled Tasks page for %q -- do not hand-edit,
# it will be overwritten the next time this task is saved.
[Unit]
Description=Rivolution scheduled task: %s

[Service]
Type=oneshot
User=rd
ExecStart=%s
`, t.Name, t.Name, execStart)

	timerContent := fmt.Sprintf(`# Generated by rivapi's Scheduled Tasks page for %q -- do not hand-edit.
[Unit]
Description=Timer for %s

[Timer]
OnCalendar=%s
Persistent=true

[Install]
WantedBy=timers.target
`, t.Name, t.Name, t.Schedule)

	stagedService, err := writeStaged("task-"+t.ID+".service", serviceContent)
	if err != nil {
		return err
	}
	stagedTimer, err := writeStaged("task-"+t.ID+".timer", timerContent)
	if err != nil {
		return err
	}

	if err := sudoRun("install", "-m", "644", stagedService, "/etc/systemd/system/"+unit+".service"); err != nil {
		return err
	}
	if err := sudoRun("install", "-m", "644", stagedTimer, "/etc/systemd/system/"+unit+".timer"); err != nil {
		return err
	}
	if err := sudoSystemctl("daemon-reload"); err != nil {
		return err
	}

	if !t.Enabled {
		return sudoSystemctl("disable", "--now", unit+".timer")
	}
	return sudoSystemctl("enable", "--now", unit+".timer")
}

// RemoveTask disables and deletes t's unit files. Best-effort on the
// disable step (fine if it was never enabled) but returns an error if the
// files themselves can't be removed.
func RemoveTask(id string) error {
	if !validTaskID(id) {
		return fmt.Errorf("internal error: invalid task ID %q", id)
	}
	unit := TaskUnitName(id)
	_ = sudoSystemctl("disable", "--now", unit+".timer") // best-effort
	if err := sudoRun("rm", "-f", "/etc/systemd/system/"+unit+".service"); err != nil {
		return err
	}
	if err := sudoRun("rm", "-f", "/etc/systemd/system/"+unit+".timer"); err != nil {
		return err
	}
	return sudoSystemctl("daemon-reload")
}

// RunTaskNow triggers t's service unit immediately, out of band from its
// timer -- lets an operator test a task without waiting for its schedule.
func RunTaskNow(id string) error {
	if !validTaskID(id) {
		return fmt.Errorf("internal error: invalid task ID %q", id)
	}
	return sudoSystemctl("start", TaskUnitName(id)+".service")
}

// TaskLastRun reports the last time id's service unit ran and whether it
// succeeded, via systemctl show -- the same read-only, no-privilege-needed
// query pattern service_status.go's unitInfo already uses.
type TaskLastRun struct {
	Ran       bool
	Succeeded bool
	When      string // systemd's own timestamp formatting, shown as-is
}

func TaskLastRunStatus(id string) TaskLastRun {
	if !validTaskID(id) {
		return TaskLastRun{}
	}
	out, err := exec.Command("systemctl", "show",
		"--property=ExecMainStatus,ExecMainExitTimestamp", TaskUnitName(id)+".service").Output()
	if err != nil {
		return TaskLastRun{}
	}
	var status, when string
	for _, line := range strings.Split(string(out), "\n") {
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		switch k {
		case "ExecMainStatus":
			status = strings.TrimSpace(v)
		case "ExecMainExitTimestamp":
			when = strings.TrimSpace(v)
		}
	}
	if when == "" {
		return TaskLastRun{}
	}
	return TaskLastRun{Ran: true, Succeeded: status == "0", When: when}
}
