package store

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// helperScriptsDir holds the three fixed, type-specific helper scripts
// (dbBackupScript/logGenScript/logReconcileScript below) -- deployed once,
// idempotently, the same regenerate-then-fixed-install pattern as
// everything else in this feature set, rather than shipped via Debian
// packaging. Each per-task systemd unit's ExecStart calls the relevant
// fixed script with that task's own arguments (backup dir/retention,
// service name/day offset) -- the script content itself never varies
// per-task, only the arguments do, so one shared script per type is
// exactly right rather than templating a new script per task.
const helperScriptsDir = "/usr/lib/rivolution/scheduled-tasks"

const dbBackupScript = `#!/bin/sh
# Generated by rivapi's Scheduled Tasks page -- do not hand-edit, it will
# be overwritten the next time any db_backup task is created or deployed.
set -e
BACKUP_DIR="$1"
RETENTION="$2"
PREFIX="$3"

HOST=$(awk -F= '/^\[mySQL\]/{f=1;next}/^\[/{f=0}f&&$1=="Hostname"{print $2}' /etc/rd.conf)
DBUSER=$(awk -F= '/^\[mySQL\]/{f=1;next}/^\[/{f=0}f&&$1=="Loginname"{print $2}' /etc/rd.conf)
PASS=$(awk -F= '/^\[mySQL\]/{f=1;next}/^\[/{f=0}f&&$1=="Password"{print $2}' /etc/rd.conf)
DB=$(awk -F= '/^\[mySQL\]/{f=1;next}/^\[/{f=0}f&&$1=="Database"{print $2}' /etc/rd.conf)

# PREFIX names the backup file; falls back to the database's own name
# (e.g. "Rivendell") if the task didn't set one.
NAME="${PREFIX:-$DB}"

mkdir -p "$BACKUP_DIR"
STAMP=$(date +%Y_%m_%d)
mysqldump -h "$HOST" -u "$DBUSER" -p"$PASS" "$DB" | gzip > "$BACKUP_DIR/${NAME}_${STAMP}.sql.gz"

# Keep only the most recent $RETENTION backups.
COUNT=$(find "$BACKUP_DIR" -name "${NAME}_*.sql.gz" | wc -l)
if [ "$COUNT" -gt "$RETENTION" ]; then
    find "$BACKUP_DIR" -name "${NAME}_*.sql.gz" | sort | head -n "$((COUNT - RETENTION))" | xargs -r rm --
fi
`

// logGenScript generates a new log (rdlogmanager -g) -- distinct from
// logMergeScript below, which merges the Traffic log into one already
// generated. The two are separate rdlogmanager modes (see its man page:
// -g requires no prior log, -t requires one to already exist) and were
// separate steps in the hand-maintained cron scripts this feature
// replaces, so they stay separate task types here too rather than one
// task trying to do both.
const logGenScript = `#!/bin/sh
# Generated by rivapi's Scheduled Tasks page -- do not hand-edit.
set -e
DAYS_OFFSET="$1"
SERVICE="$2"
/usr/bin/rdlogmanager -P -g -d "$DAYS_OFFSET" -s "$SERVICE"
`

const logMergeScript = `#!/bin/sh
# Generated by rivapi's Scheduled Tasks page -- do not hand-edit.
set -e
DAYS_OFFSET="$1"
SERVICE="$2"
/usr/bin/rdlogmanager -P -d "$DAYS_OFFSET" -t -s "$SERVICE"
`

const logReconcileScript = `#!/bin/sh
# Generated by rivapi's Scheduled Tasks page -- do not hand-edit.
set -e
SERVICE="$1"
/usr/bin/rdlogmanager -r Reconcile -s "$SERVICE"
`

// controlScriptsDir holds three more fixed helper scripts -- unlike the
// three above (which run *as* a task, unprivileged, as rd), these run
// *through sudo* to install/remove/control a task's systemd unit files.
//
// Ubuntu 26.04 ships sudo-rs (Ubuntu's Rust reimplementation of sudo, `sudo
// -V` reports "sudo-rs"), which enforces "wildcards are not allowed in
// command arguments" as a hard parser error -- confirmed 2026-07-04 on a
// real install, where conf/sudoers.d/rivapi's task-*.service/task-*.timer/
// rivolution-task-*.timer wildcarded Cmnd_Alias entries failed to parse
// entirely, silently dropping every NOPASSWD rule in the file (all sudo
// commands fell back to a password prompt, not a lockout, but a real
// regression). Traditional GNU sudo allows fnmatch-style wildcards in
// command arguments; sudo-rs deliberately doesn't. Since task IDs vary per
// task, the destination unit filename can't be expressed as a fixed
// sudoers argument -- so the specificity moves into these scripts instead:
// each is whitelisted in sudoers by its bare path only (no arguments
// specified in the Cmnd_Alias, which grants running it with *any*
// arguments), and each one validates its own arguments internally (the
// same 16-hex-character task ID shape store.validTaskID already checks in
// Go, checked again here in shell as defense in depth) before touching any
// file.
const controlScriptsDir = "/usr/lib/rivolution/control-scripts"

// taskIDShellPattern is a case(1) glob matching exactly 16 lowercase hex
// characters -- the shell-side twin of Go's idRe, used inside every
// control script below.
const taskIDCasePattern = `[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]`

var installUnitScript = `#!/bin/sh
# install-unit.sh <staged-file> <task-id> <service|timer>
# Generated by rivapi -- do not hand-edit, overwritten on next deploy.
set -e
STAGED="$1"
ID="$2"
KIND="$3"
case "$ID" in
    ` + taskIDCasePattern + `) ;;
    *) echo "install-unit.sh: invalid task id" >&2; exit 1 ;;
esac
case "$KIND" in
    service|timer) ;;
    *) echo "install-unit.sh: invalid unit kind" >&2; exit 1 ;;
esac
install -m 644 "$STAGED" "/etc/systemd/system/rivolution-task-${ID}.${KIND}"
`

var removeUnitScript = `#!/bin/sh
# remove-unit.sh <task-id>
# Generated by rivapi -- do not hand-edit, overwritten on next deploy.
set -e
ID="$1"
case "$ID" in
    ` + taskIDCasePattern + `) ;;
    *) echo "remove-unit.sh: invalid task id" >&2; exit 1 ;;
esac
systemctl disable --now "rivolution-task-${ID}.timer" 2>/dev/null || true
rm -f "/etc/systemd/system/rivolution-task-${ID}.service" "/etc/systemd/system/rivolution-task-${ID}.timer"
`

var taskSystemctlScript = `#!/bin/sh
# task-systemctl.sh <enable|disable|start> <task-id>
# Generated by rivapi -- do not hand-edit, overwritten on next deploy.
set -e
ACTION="$1"
ID="$2"
case "$ID" in
    ` + taskIDCasePattern + `) ;;
    *) echo "task-systemctl.sh: invalid task id" >&2; exit 1 ;;
esac
case "$ACTION" in
    enable) systemctl enable --now "rivolution-task-${ID}.timer" ;;
    disable) systemctl disable --now "rivolution-task-${ID}.timer" ;;
    start) systemctl start "rivolution-task-${ID}.service" ;;
    *) echo "task-systemctl.sh: invalid action" >&2; exit 1 ;;
esac
`

// ensureControlScripts deploys all three control scripts if any is missing
// or stale -- same idempotent, called-before-every-use pattern as
// ensureHelperScript.
func ensureControlScripts() error {
	scripts := map[string]string{
		"install-unit.sh":   installUnitScript,
		"remove-unit.sh":    removeUnitScript,
		"task-systemctl.sh": taskSystemctlScript,
	}
	for name, content := range scripts {
		path := controlScriptsDir + "/" + name
		if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
			continue
		}
		if err := sudoRun("mkdir", "-p", controlScriptsDir); err != nil {
			return err
		}
		staged, err := writeStaged("control-"+name, content)
		if err != nil {
			return err
		}
		if err := sudoRun("install", "-m", "755", staged, path); err != nil {
			return err
		}
	}
	return nil
}

func helperScriptPath(t TaskType) string {
	switch t {
	case TaskDBBackup:
		return helperScriptsDir + "/db-backup.sh"
	case TaskLogGen:
		return helperScriptsDir + "/log-gen.sh"
	case TaskLogMerge:
		return helperScriptsDir + "/log-merge.sh"
	case TaskLogReconcile:
		return helperScriptsDir + "/log-reconcile.sh"
	default:
		return ""
	}
}

func helperScriptContent(t TaskType) string {
	switch t {
	case TaskDBBackup:
		return dbBackupScript
	case TaskLogGen:
		return logGenScript
	case TaskLogMerge:
		return logMergeScript
	case TaskLogReconcile:
		return logReconcileScript
	default:
		return ""
	}
}

// ensureHelperScript deploys the fixed helper script for t if it isn't
// already present with the current content -- idempotent, called before
// every deploy so an upgraded rivapi binary's updated script content
// always reaches the box the next time any task of that type is touched.
func ensureHelperScript(t TaskType) error {
	path := helperScriptPath(t)
	if path == "" {
		return nil // TaskCustom has no fixed helper script
	}
	content := helperScriptContent(t)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		return nil
	}
	if err := sudoRun("mkdir", "-p", helperScriptsDir); err != nil {
		return err
	}
	staged, err := writeStaged("helper-"+string(t)+".sh", content)
	if err != nil {
		return err
	}
	if err := sudoRun("install", "-m", "755", staged, path); err != nil {
		return err
	}
	return nil
}

// execStartFor returns the ExecStart= command line for t, given its own
// configured arguments. CustomCommand is operator-authored, run via
// /bin/sh -c: the operator is the trusted admin of their own box entering
// their own command to run periodically, the same trust boundary crontab
// itself already grants them today -- see BACKLOG.md's tracked gap this
// page replaces.
func execStartFor(t ScheduledTask) (string, error) {
	switch t.Type {
	case TaskDBBackup:
		if t.BackupDir == "" || t.RetentionDays <= 0 {
			return "", fmt.Errorf("db_backup task needs a backup directory and a positive retention count")
		}
		prefix := t.FilePrefix
		if prefix == "" {
			// systemd's ExecStart= line splits on whitespace like a shell;
			// a bare empty arg would just vanish, dropping positional $3
			// entirely and shifting nothing (there's nothing after it) --
			// but relying on that would be fragile if a field were ever
			// added after FilePrefix. `""` is systemd's own quoting for
			// an explicit empty argument (systemd.service(5), "command
			// lines"), so $3 in the script really is "" and PREFIX:-$DB
			// falls back to $DB as intended.
			prefix = `""`
		}
		return fmt.Sprintf("%s %s %d %s", helperScriptPath(TaskDBBackup), t.BackupDir, t.RetentionDays, prefix), nil
	case TaskLogGen:
		if t.ServiceName == "" {
			return "", fmt.Errorf("log_gen task needs a Rivendell service name")
		}
		return fmt.Sprintf("%s %d %s", helperScriptPath(TaskLogGen), t.DaysOffset, t.ServiceName), nil
	case TaskLogMerge:
		if t.ServiceName == "" {
			return "", fmt.Errorf("log_merge task needs a Rivendell service name")
		}
		return fmt.Sprintf("%s %d %s", helperScriptPath(TaskLogMerge), t.DaysOffset, t.ServiceName), nil
	case TaskLogReconcile:
		if t.ServiceName == "" {
			return "", fmt.Errorf("log_reconcile task needs a Rivendell service name")
		}
		return fmt.Sprintf("%s %s", helperScriptPath(TaskLogReconcile), t.ServiceName), nil
	case TaskCustom:
		if strings.TrimSpace(t.CustomCommand) == "" {
			return "", fmt.Errorf("custom task needs a command")
		}
		return "/bin/sh -c " + shellQuote(t.CustomCommand), nil
	default:
		return "", fmt.Errorf("unknown task type %q", t.Type)
	}
}

// shellQuote wraps s in single quotes for safe use as one systemd
// ExecStart= argument, escaping any single quote s itself contains.
// Standard POSIX-shell single-quote escaping: close the quote, emit an
// escaped literal quote, reopen the quote.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// DeployTask (re)generates and installs t's service+timer unit pair, then
// enables the timer. Safe to call again for an existing task (e.g. after
// editing its schedule) -- systemd overwrites/reloads cleanly either way.
func DeployTask(t ScheduledTask) error {
	if !validTaskID(t.ID) {
		return fmt.Errorf("internal error: invalid task ID %q", t.ID)
	}
	if strings.TrimSpace(t.Schedule) == "" {
		return fmt.Errorf("task needs a schedule (systemd OnCalendar= expression)")
	}

	if err := ensureHelperScript(t.Type); err != nil {
		return fmt.Errorf("deploying helper script: %w", err)
	}
	if err := ensureControlScripts(); err != nil {
		return fmt.Errorf("deploying control scripts: %w", err)
	}

	execStart, err := execStartFor(t)
	if err != nil {
		return err
	}

	serviceContent := fmt.Sprintf(`# Generated by rivapi's Scheduled Tasks page for %q -- do not hand-edit,
# it will be overwritten the next time this task is saved.
[Unit]
Description=Rivolution scheduled task: %s

[Service]
Type=oneshot
User=rd
ExecStart=%s
`, t.Name, t.Name, execStart)

	timerContent := fmt.Sprintf(`# Generated by rivapi's Scheduled Tasks page for %q -- do not hand-edit.
[Unit]
Description=Timer for %s

[Timer]
OnCalendar=%s
Persistent=true

[Install]
WantedBy=timers.target
`, t.Name, t.Name, t.Schedule)

	stagedService, err := writeStaged("task-"+t.ID+".service", serviceContent)
	if err != nil {
		return err
	}
	stagedTimer, err := writeStaged("task-"+t.ID+".timer", timerContent)
	if err != nil {
		return err
	}

	controlScript := controlScriptsDir + "/install-unit.sh"
	if err := sudoRun(controlScript, stagedService, t.ID, "service"); err != nil {
		return err
	}
	if err := sudoRun(controlScript, stagedTimer, t.ID, "timer"); err != nil {
		return err
	}
	if err := sudoSystemctl("daemon-reload"); err != nil {
		return err
	}

	taskCtl := controlScriptsDir + "/task-systemctl.sh"
	if !t.Enabled {
		return sudoRun(taskCtl, "disable", t.ID)
	}
	return sudoRun(taskCtl, "enable", t.ID)
}

// RemoveTask disables and deletes t's unit files via remove-unit.sh (see
// ensureControlScripts) -- both steps happen inside that one script so a
// task ID only ever needs validating once per call.
func RemoveTask(id string) error {
	if !validTaskID(id) {
		return fmt.Errorf("internal error: invalid task ID %q", id)
	}
	if err := ensureControlScripts(); err != nil {
		return fmt.Errorf("deploying control scripts: %w", err)
	}
	if err := sudoRun(controlScriptsDir+"/remove-unit.sh", id); err != nil {
		return err
	}
	return sudoSystemctl("daemon-reload")
}

// RunTaskNow triggers t's service unit immediately, out of band from its
// timer -- lets an operator test a task without waiting for its schedule.
func RunTaskNow(id string) error {
	if !validTaskID(id) {
		return fmt.Errorf("internal error: invalid task ID %q", id)
	}
	if err := ensureControlScripts(); err != nil {
		return fmt.Errorf("deploying control scripts: %w", err)
	}
	return sudoRun(controlScriptsDir+"/task-systemctl.sh", "start", id)
}

// TaskLastRun reports the last time id's service unit ran and whether it
// succeeded, via systemctl show -- the same read-only, no-privilege-needed
// query pattern service_status.go's unitInfo already uses.
type TaskLastRun struct {
	Ran       bool
	Succeeded bool
	When      string // systemd's own timestamp formatting, shown as-is
}

func TaskLastRunStatus(id string) TaskLastRun {
	if !validTaskID(id) {
		return TaskLastRun{}
	}
	out, err := exec.Command("systemctl", "show",
		"--property=ExecMainStatus,ExecMainExitTimestamp", TaskUnitName(id)+".service").Output()
	if err != nil {
		return TaskLastRun{}
	}
	var status, when string
	for _, line := range strings.Split(string(out), "\n") {
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		switch k {
		case "ExecMainStatus":
			status = strings.TrimSpace(v)
		case "ExecMainExitTimestamp":
			when = strings.TrimSpace(v)
		}
	}
	if when == "" {
		return TaskLastRun{}
	}
	return TaskLastRun{Ran: true, Succeeded: status == "0", When: when}
}
